services:
  mongodb_container:
    image: mongo:latest
  environment:
    MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  ports:
    - 27017:27017
  volumes:
    - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
