services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/conf:/etc/nginx/conf.d
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/certs:/etc/nginx/certs
    networks:
      - proxy
    environment:
      NGINX_PROXY_CONTAINER: proxy
      DEFAULT_HOST: app.dev
      DHPARAM_GENERATION: "false"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  # letsencrypt:
  #   container_name: letsencrypt
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   restart: always
  #   volumes:
  #     - ./data/conf:/etc/nginx/conf.d
  #     - ./data/vhost:/etc/nginx/vhost.d
  #     - ./data/html:/usr/share/nginx/html
  #     - ./data/certs:/etc/nginx/certs
  #     - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  proxy:
    name: proxy
