services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: midb
      MYSQL_USER: miusuario
      MYSQL_PASSWORD: mipass123
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped